// Fastify plugin autogenerated by fastify-swaggergen
const plugin = require("fastify-swaggergen");

const options = {
  swaggerSpec: `${__dirname}/swagger.json`,
  service: `${__dirname}/service.js`,
  fastifySwagger: {
    disabled: false
  }
};

module.exports = async function(fastify, opts) {
  fastify.register(plugin, options);
};
