// Fastify plugin autogenerated by fastify-swaggergen
const swaggerGen = require("../../index.js");

const options = {
  swaggerSpec: `${__dirname}/swagger.json`,
  service: `${__dirname}/service.js`,
  fastifySwagger: {
    disabled: false
  }
};

module.exports = async function(fastify, opts) {
  fastify.register(swaggerGen, options);
};
