module.exports = data => `// Fastify plugin autogenerated by fastify-swaggergen
const plugin = require("${data.pluginPackageName}");

const options = {
  swaggerSpec: \`\${__dirname}/${data.specFile}\`,
  service: \`\${__dirname}/${data.service}\`,
  fastifySwagger: {
    disabled: false
  }
};

module.exports = async function(fastify, opts) {
  fastify.register(plugin, options);
};
`;
