module.exports = (projectName, instructions) => `# ${projectName}

This directory contains a fastify plugin that was autogenerated using 
[fastify-swaggergen](https://github.com/seriousme/fastify-swaggergen) and 
the swagger specifation in [swagger.json](swagger.json)
${instructions}
`;
