module.exports = (projectName, instructions) => `# ${projectName}

This directory contains a fastify plugin that was autogenerated using 
[fastify-swaggergen](https://github.com/seriousme/fastify-swaggergen) and 
the OpenApi specifation in [openApi.json](openApi.json)
${instructions}
`;
